//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubEnj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int id_table { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_config { get; set; }
        public Nullable<int> spaciousness { get; set; }
    
        public virtual Config Config { get; set; }
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
