//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prise
    {
        public int id_prise { get; set; }
        public string prise1 { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual User User { get; set; }
    }
}
